// A set of helper function for generating updateBatch commands

// Generates an array of commands to insert text lines to the main body of the document
function insertTextLines(firstStartLocation: number, textLines: string[], styles: object[]) {
  const commands = [];
  let startLocation = firstStartLocation;
  textLines.forEach((line, idx) => {
    commands.push(
      insertTextLine(startLocation, line)
    );

    if (Object.keys(styles[idx]).length) {
      commands.push(
        applyTextStyle(startLocation, startLocation + line.length, styles[idx])
      );
    }

    startLocation += line.length + 1;
  });

  return commands;
}

function applyTextStyle(startLocation: number, endLocation: number, style: object) {
  return {
    updateTextStyle: {
      range: {
        startIndex: startLocation,
        endIndex: endLocation
      },
      textStyle: style,
      fields: '*'
    }
  };
}

function generateFontSize(ptSize: number) {
  return {
    magnitude: ptSize,
    unit: 'PT'
  }
}

// Generates a command to insert text to the main body of the document
function insertTextLine(startLocation: number, text: string) {
  return {
    insertText: {
      text: text + '\n',
      location: {
        index: startLocation
      }
    }
  }
}

// Convenience function to generate the update necessary to replace / amend a line of content
function updateContentLine(oldLine: string, newLine: string) {
  if (!oldLine) {
    return {
      insertText: {
        text: newLine + '\n',
        endOfSegmentLocation: {} // Indicates amend to end of doc
      }
    };
  }

  return {
    replaceAllText: {
      replaceText: newLine,
      containsText: {
        text: oldLine,
        matchCase: true
      }
    }
  };
}

function generateHeaderCommands(documentId) {
  const importUrl = `https://jon-simpkins.github.io/revision/#/writing?storyId=${documentId}`

  return insertTextLines(1,
    [
      'Story created in Revision!',
      '',
      '',
      'Do NOT edit this file directly, as doing so might cause Revision to be unable to open it again.',
      '',
      'The intention of storing this document in Google Docs is to clearly delegate all ownership of the content to you, '
        + 'and to allow your exclusive ability to modify the list of folks who can collaborate or view it.',
      '',
      `To import to Revision, simply navigate to:`,
      importUrl,
      '',
      '--------------------------',
      ''
    ],
    [
      {bold: true, fontSize: generateFontSize(18)},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {underline: true, foregroundColor: {color: {rgbColor: {red: 0.06666667, green: 0.33333334, blue: 0.8}}}, link: {url: importUrl}},
      {},
      {bold: true},
      {}
    ]
  );
}

export {generateHeaderCommands, updateContentLine};
