enum ScrapPrototype {
  MOVIE_TITLE,
  SIMILAR_MOVIES,
  LOG_LINE,
  TIME_FRAME,
  CHARACTER_LISTING,
  CHARACTER_NAME,
  CHARACTER_GENDER,
  CHARACTER_DRIVE,
  MOVIE_DURATION,
  STRUCTURE_SPEC,
  STRUCTURE_BLOCK_SUMMARY,
  STRUCTURE_BLOCK_CONTENT,
  SCRIPT,
  QUESTIONS_TO_EXPLORE,
};

export default ScrapPrototype;
